version: '3.8'

services:
  weather-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "weather-app"
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./dist:/var/www/html
    networks:
      - matchanalyzer_ma_backend
networks:
  matchanalyzer_ma_backend:
    external: true
